### ISSUE TITLE
All Players keep getting kick when someone who drank a polymorph potion joins

### ISSUE THREAD

**Issue by OrBlank** [Ladysnake/Impersonate#34] opened 2023-06-03 18:44 UTC
Some players on my server drank a bewitchment polymorph potion and whenever they try joining, it kicks all the other players out of the server. The server doesn't crash and it doesn't seem like anything important shows up in the console.

Log of the situation:
[Gist Link](https://gist.github.com/OrBlank/24ae376c96e2b17ff3656b65131ae68c)

**Comment by Pyrofab** [comment] 2023-06-27 23:28
Almost definitely a duplicate of #33

**Closed as not planned by Pyrofab** 2023-06-27 23:28 UTC
